name: ci

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - uses: actions/checkout@v4

      # 1) Enable Corepack & activate the exact pnpm version from package.json
      - name: Enable Corepack / pnpm
        run: |
          node --version
          corepack enable
          PNPM_VERSION=$(node -e "try {
            const pkg = require('./package.json');
            const pm = pkg.packageManager || '';
            const match = pm.match(/^pnpm@(.+)$/);
            if (match) { console.log(match[1]); }
            else { console.warn('Warning: packageManager field missing or not pnpm@version, using fallback pnpm version'); console.log('8.6.12'); }
          } catch (e) { console.warn('Warning: failed to read package.json, using fallback pnpm version'); console.log('8.6.12'); }")
          corepack prepare pnpm@${PNPM_VERSION} --activate
          pnpm --version

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Prettier check
        run: pnpm format:check

      - name: ESLint
        run: pnpm lint

      - name: Type check
        run: pnpm ts:check

      - name: Tests (Vitest + coverage)
        run: pnpm test:coverage

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

      # Build only on pushes (skip on PR for speed)
      - name: Build
        if: github.event_name == 'push'
        run: pnpm build
